class Teste1 {
    public static void main(String[] args) {
        //Esqueci de incluir o comentário 1...
	//Adiconei o comentário 3 antes do Comentário 3.....
        //Esqueci de incluir o comentário 2...
        System.out.println("Hello World!!!!");
    }
}

